services:
  - type: web
    name: nexopos
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev
      php artisan key:generate
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromService:
          type: mysql
          name: nexopos-db
          property: host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: nexopos_db
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        fromService:
          type: mysql
          name: nexopos-db
          property: password

databases:
  - name: nexopos-db
    plan: free
    databaseName: nexopos_db
