services:
  - type: web
    name: AllBiz-POS
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromService:
          type: pserv
          name: allbizdb
          property: host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: allbizdb
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        fromService:
          type: pserv
          name: AllBiz-POS
          property: connectionString

databases:
  - name: AllBiz-POS
    plan: free
    databaseName: allbizdb
    
    
