services:
  - type: web
    name: nexopos
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromService:
          type: pserv
          name: nexopos-db
          property: host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: nexopos_db
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        fromService:
          type: pserv
          name: nexopos-db
          property: connectionString

databases:
  - name: nexopos-db
    plan: free
    databaseName: nexopos_db
